### ISSUE TITLE
Armitage not starting and showing a blank message

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Kaicastledine/armitage#79]
```
What steps will reproduce the problem?
1. Install Metasploit and update it
2. Type "armitage" in console and go through the first windows
3. Wait for the connection to establish

What is the expected output? What do you see instead?
Armitage should start instead I see a blank message (it's an empty window) and 
the process just stucks there forever saying that the connection is established.


What version of Metasploit are you using? 4.1.4
On which operating system? OpenSUSE 12.1 x65

Which database are you using? None? (dunno, just followed the guide)

Thanks for helping,
Alessio



Please provide any additional information below.





```

Original issue reported on code.google.com by `alessio...@gmail.com` on 15 Dec 2011 at 11:26

Attachments:
- [armitage-bug.png](https://storage.googleapis.com/google-code-attachments/armitage/issue-79/comment-0/armitage-bug.png)

**Comment by GoogleCodeExporter** [comment]
```
Follow the database troubleshooting steps in the guide. I suspect that this is 
what it relates to. Not sure why you're getting a blank message though.
```

Original comment by `rsmu...@gmail.com` on 15 Dec 2011 at 4:16

**Comment by GoogleCodeExporter** [comment]
```
Oh and by the way, since you're using Metasploit 4.1.4 I guarantee it's a 
database issue. If you rebooted after install, your database server is no 
longer running. This is because Metasploit 4.1.4 doesn't start it up on boot 
unless you opt to start all of the commercial stuff too. I have a work-around 
for this in the troubleshooting guide. Click the Help button in the connect 
dialog to reach it.
```

Original comment by `rsmu...@gmail.com` on 15 Dec 2011 at 4:24

**Comment by GoogleCodeExporter** [comment]
```
I'm trying to reproduce that silly blank dialog, but I can't. It's definitely 
the database because it's the same size as the 'database is not running" 
message. It being blank though is what confuses me. There's no button and no 
information icon.

Does it always come up blank like this for you or did it just happen this way 
once? When I see this it looks like a deadlock occurred. If you're really 
saavy, do a kill -3 on the java process id for armitage and send me the output. 

If you just want to fix your issue, def. check the troubleshooting guide.
```

Original comment by `rsmu...@gmail.com` on 15 Dec 2011 at 4:48

**Comment by GoogleCodeExporter** [comment]
```
same issue, osx box, pg 9.1, db runs fine under msfconsole/etc.

$ java -version
java version "1.6.0_29"
Java(TM) SE Runtime Environment (build 1.6.0_29-b11-402-10M3527)
Java HotSpot(TM) 64-Bit Server VM (build 20.4-b02-402, mixed mode)


Macintosh:trunk mike$ sudo ./armitage 
Starting msfrpcd for you.
[*] MSGRPC starting on 127.0.0.1:55553 (SSL):Msg...
/opt/local/lib/ruby1.9/1.9.1/rubygems/custom_require.rb:36:in `require': iconv 
will be deprecated in the future, use String#encode instead.
2012-01-01 11:20:33
Full thread dump Java HotSpot(TM) 64-Bit Server VM (20.4-b02-402 mixed mode):

"fork of util.sl:338-372" prio=1 tid=101c36800 nid=0x122c2b000 waiting on 
condition [122c2a000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at sleep.bridges.BasicIO$sleep.evaluate(Unknown Source)
        at sleep.engine.CallRequest$FunctionCallRequest.execute(Unknown Source)
        at sleep.engine.CallRequest.CallFunction(Unknown Source)
        at sleep.engine.atoms.Call.evaluate(Unknown Source)
        at sleep.engine.Block.evaluate(Unknown Source)
        at sleep.engine.Block.evaluate(Unknown Source)
        at sleep.engine.atoms.Goto.evaluate(Unknown Source)
        at sleep.engine.Block.evaluate(Unknown Source)
        at sleep.engine.Block.evaluate(Unknown Source)
        at sleep.bridges.SleepClosure.evaluate(Unknown Source)
        - locked <7f40e3478> (a sleep.runtime.ScriptVariables)
        at sleep.engine.CallRequest$ClosureCallRequest.execute(Unknown Source)
        at sleep.engine.CallRequest.CallFunction(Unknown Source)
        at sleep.runtime.SleepUtils.runCode(Unknown Source)
        - locked <7f40e3478> (a sleep.runtime.ScriptVariables)
        at sleep.runtime.SleepUtils.runCode(Unknown Source)
        at sleep.runtime.ScriptInstance.runScript(Unknown Source)
        at sleep.runtime.ScriptInstance.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:680)

"process reaper" daemon prio=6 tid=101c96800 nid=0x122b28000 runnable 
[122b27000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.UNIXProcess.waitForProcessExit(Native Method)
        at java.lang.UNIXProcess.access$900(UNIXProcess.java:17)
        at java.lang.UNIXProcess$2$1.run(UNIXProcess.java:86)

"Thread-5" prio=6 tid=1099e3800 nid=0x121433000 in Object.wait() [121431000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <7f4545500> (a java.awt.Component$AWTTreeLock)
        at java.lang.Object.wait(Object.java:485)
        at java.awt.Dialog.show(Dialog.java:1109)
        - locked <7f4545500> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:853)
        at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:650)
        at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:621)
        at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:592)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at sleep.engine.atoms.ObjectAccess$MethodCallRequest.execute(Unknown Source)
        at sleep.engine.CallRequest.CallFunction(Unknown Source)
        at sleep.engine.atoms.ObjectAccess.evaluate(Unknown Source)
        at sleep.engine.Block.evaluate(Unknown Source)
        at sleep.engine.Block.evaluate(Unknown Source)
        at sleep.engine.Block.handleException(Unknown Source)
        at sleep.engine.Block.evaluate(Unknown Source)
        at sleep.engine.Block.evaluate(Unknown Source)
        at sleep.engine.atoms.Try.evaluate(Unknown Source)
        at sleep.engine.Block.evaluate(Unknown Source)
        at sleep.engine.Block.evaluate(Unknown Source)
        at sleep.engine.atoms.Decide.evaluate(Unknown Source)
        at sleep.engine.Block.evaluate(Unknown Source)
        at sleep.engine.Block.evaluate(Unknown Source)
        at sleep.bridges.SleepClosure.evaluate(Unknown Source)
        - locked <7f44e10a0> (a sleep.runtime.ScriptVariables)
        at sleep.engine.ProxyInterface.invoke(Unknown Source)
        - locked <7f44e10a0> (a sleep.runtime.ScriptVariables)
        at $Proxy1.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:680)

"TimerQueue" daemon prio=5 tid=101801800 nid=0x11f6f5000 in Object.wait() 
[11f6f4000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <7f40f8c48> (a javax.swing.TimerQueue)
        at javax.swing.TimerQueue.run(TimerQueue.java:232)
        - locked <7f40f8c48> (a javax.swing.TimerQueue)
        at java.lang.Thread.run(Thread.java:680)

"DestroyJavaVM" prio=5 tid=109c3c000 nid=0x100601000 waiting on condition 
[00000000]
   java.lang.Thread.State: RUNNABLE

"AWT-EventQueue-0" prio=6 tid=1224fd800 nid=0x11ebc6000 waiting for monitor 
entry [11ebc4000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at sleep.engine.ProxyInterface.invoke(Unknown Source)
        - waiting to lock <7f44e10a0> (a sleep.runtime.ScriptVariables)
        at $Proxy1.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:677)
        at java.awt.EventQueue.access$000(EventQueue.java:85)
        at java.awt.EventQueue$1.run(EventQueue.java:638)
        at java.awt.EventQueue$1.run(EventQueue.java:636)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:647)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

"Poller SunPKCS11-Darwin" daemon prio=1 tid=109c08800 nid=0x11eac3000 waiting 
on condition [11eac2000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at sun.security.pkcs11.SunPKCS11$TokenPoller.run(SunPKCS11.java:692)
        at java.lang.Thread.run(Thread.java:680)

"Java2D Disposer" daemon prio=10 tid=10ba4e800 nid=0x121330000 in Object.wait() 
[12132f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <7f40fc4e0> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:118)
        - locked <7f40fc4e0> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:134)
        at sun.java2d.Disposer.run(Disposer.java:127)
        at java.lang.Thread.run(Thread.java:680)

"AWT-Shutdown" prio=5 tid=1019fa000 nid=0x11d601000 in Object.wait() [11d600000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <7f44e7210> (a java.lang.Object)
        at java.lang.Object.wait(Object.java:485)
        at sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:265)
        - locked <7f44e7210> (a java.lang.Object)
        at java.lang.Thread.run(Thread.java:680)

"AWT-AppKit" daemon prio=5 tid=101971000 nid=0x7fff70980cc0 runnable [00000000]
   java.lang.Thread.State: RUNNABLE

"Low Memory Detector" daemon prio=5 tid=10b800000 nid=0x10a790000 runnable 
[00000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" daemon prio=9 tid=1018dd800 nid=0x10a68d000 waiting on 
condition [00000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" daemon prio=9 tid=1018dc800 nid=0x10a58a000 waiting on 
condition [00000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" daemon prio=9 tid=1018dc000 nid=0x10a487000 waiting on 
condition [00000000]
   java.lang.Thread.State: RUNNABLE

"Surrogate Locker Thread (Concurrent GC)" daemon prio=5 tid=1018db000 
nid=0x10a384000 waiting on condition [00000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" daemon prio=8 tid=1018d2800 nid=0x1097ea000 in Object.wait() 
[1097e9000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <7f44e12a8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:118)
        - locked <7f44e12a8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:134)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:159)

"Reference Handler" daemon prio=10 tid=1018d1800 nid=0x1096e7000 in 
Object.wait() [1096e6000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <7f44e12c0> (a java.lang.ref.Reference$Lock)
        at java.lang.Object.wait(Object.java:485)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:116)
        - locked <7f44e12c0> (a java.lang.ref.Reference$Lock)

"VM Thread" prio=9 tid=1018cd000 nid=0x1095e4000 runnable 

"Gang worker#0 (Parallel GC Threads)" prio=9 tid=101802800 nid=0x1017f9000 
runnable 

"Gang worker#1 (Parallel GC Threads)" prio=9 tid=101803800 nid=0x102401000 
runnable 

"Gang worker#2 (Parallel GC Threads)" prio=9 tid=101804000 nid=0x102504000 
runnable 

"Gang worker#3 (Parallel GC Threads)" prio=9 tid=101804800 nid=0x102607000 
runnable 

"Concurrent Mark-Sweep GC Thread" prio=9 tid=10187f800 nid=0x1092f0000 runnable 
"VM Periodic Task Thread" prio=10 tid=10b812000 nid=0x10b301000 waiting on 
condition 

"Exception Catcher Thread" prio=10 tid=101802000 nid=0x100704000 runnable 
JNI global references: 1790

Heap
 par new generation   total 19136K, used 11387K [7f3000000, 7f44c0000, 7f44c0000)
  eden space 17024K,  54% used [7f3000000, 7f390eeb0, 7f40a0000)
  from space 2112K, 100% used [7f40a0000, 7f42b0000, 7f42b0000)
  to   space 2112K,   0% used [7f42b0000, 7f42b0000, 7f44c0000)
 concurrent mark-sweep generation total 63872K, used 4011K [7f44c0000, 7f8320000, 7fae00000)
 concurrent-mark-sweep perm gen total 22592K, used 22569K [7fae00000, 7fc410000, 800000000)


```

Original comment by `mike.lea...@gmail.com` on 1 Jan 2012 at 12:24

**Comment by GoogleCodeExporter** [comment]
```
Try running it as root.

```

Original comment by `rsmu...@gmail.com` on 1 Jan 2012 at 12:47

**Comment by GoogleCodeExporter** [comment]
```
it was being ran as root, note the sudo.

running it from a root shell gives the same error :/

Macintosh:trunk mike$ sudo sh
sh-3.2# ./armitage 
sh-3.2# id
uid=0(root) gid=0(wheel) ...

note this is snow-leopard, not lion

```

Original comment by `mike.lea...@gmail.com` on 1 Jan 2012 at 7:05

**Comment by GoogleCodeExporter** [comment]
```
note that my error box is significantly smaller than in that image, its only 
slightly larger than the Loading image (See attach)
```

Original comment by `mike.lea...@gmail.com` on 1 Jan 2012 at 7:07

Attachments:
- [error.jpg](https://storage.googleapis.com/google-code-attachments/armitage/issue-79/comment-7/error.jpg)

**Comment by GoogleCodeExporter** [comment]
```
Ok, two things:

1) I don't provide support for Metasploit on MacOS X. You're really on your own 
here. I appreciate you taking the time to post a screenshot and respond to my 
follow up, but I'm not going to try to figure out what this is on MacOS X.

2) I'm unable to reproduce the blank dialog and believe me, I've tried doing 
many things "wrong" in an attempt to do so. The only thing I haven't done is 
setup Metasploit by hand (I use the full setup installer and that's what I 
require from others who want my help with their environment). I can tell you 
what it wants to say though. Armitage can't connect to your database. Why? No 
idea, you'll have to figure this out [again, you're way outside of the area of 
what I provide support for]. I can give you a few hints that may help though. 
Armitage looks for a file YAML file that species how to connect to your 
database. It finds this file through the MSF_DATABASE_CONFIG environment 
variable. More info is in Section 2.5 and 2.6 of the manual.
 http://www.fastandeasyhacking.com/manual#1 
```

Original comment by `rsmu...@gmail.com` on 1 Jan 2012 at 8:45

**Comment by GoogleCodeExporter** [comment]
```
Sure thing, i understand re support on osx etc, i'm trying to nut this out so 
it helps all others on osx.

i've been using the yaml/db config, and msf grabs it all fine, so i suspect its 
something else other than basic config.

could it perhaps be an ssl thing?
under osx postgre doesn't use ssl by default.

using -S on msfrpcd (to disable ssl, armitage shows the ssl exception, then 
when reloading rpcd with ssl enabled, i get the blank error message, so it 
seems beyond that ssl negotiation phase.

thanks for your help 


```

Original comment by `mike.lea...@gmail.com` on 2 Jan 2012 at 6:40

**Comment by GoogleCodeExporter** [comment]
```
MSF might pick it up fine, but Armitage has to pick it up too.
```

Original comment by `rsmu...@gmail.com` on 2 Jan 2012 at 6:53

**Comment by GoogleCodeExporter** [comment]
```
I've finally reproduced the blank dialog! I had to do a bunch of things for 
this to happen, but... I reproduced it.

Here's what I did:

0) I installed Metasploit using the full setup installer for Linux -- check.

1) I started Metasploit's RPC daemon using sudo msfrpcd blah blah blah. This is 
all well and good because Metasploit's RPC daemon was now running as root.

2) As a *user* without privileges, I started Armitage using java -jar 
armitage.jar. I did this by downloading armitage from fastandeasyhacking.com 
and using the Java installed with Ubuntu Linux.

3) I tried to connect Armitage to the Metasploit I started separately. 

And voila...

Blank dialog.

Now I know the problem. The next Armitage update will prompt with a sane error 
message. But for you guys, here's what you need to know:

The database.yml file is setup by Metasploit to be readable only by a user with 
superuser privileges. If Armitage connects to Metasploit locally, it needs to 
read this file to figure out how to connect to the database. Armitage talks to 
the database directly now. 

When Armitage (run as a non-privileged user) tries to read this file, you end 
up with this blank error. 

user@ubuntu:~$ ls -alh /opt/metasploit-4.1.4/config/
total 16K
drwxr-xr-x  3 root root 4.0K 2011-12-30 00:02 .
drwxr-xr-x 14 root root 4.0K 2011-12-30 00:03 ..
-rwx------  1 root root  467 2011-12-30 00:02 database.yml
drwxr-xr-x  3 root root 4.0K 2011-12-30 00:01 svn

Sorry it took so long to track down guys. I really tried a lot of things 
before. I hope this helps!

```

Original comment by `rsmu...@gmail.com` on 2 Jan 2012 at 8:33

Attachments:
- [sucks.png](https://storage.googleapis.com/google-code-attachments/armitage/issue-79/comment-11/sucks.png)

**Comment by GoogleCodeExporter** [comment]
```
Also, I've updated section 2.4 of the manual to state that armitage must also 
be started as root.
```

Original comment by `rsmu...@gmail.com` on 2 Jan 2012 at 8:37

**Comment by GoogleCodeExporter** [comment]
```
Ok, I've updated my code to detect this situation and be a little more helpful 
(and non-freezing).
And... here's the change in the code: 
http://code.google.com/p/armitage/source/detail?r=569

I'll probably have an update out later this week. I have a few other things I'd 
like to address before I push a release though.
```

Original comment by `rsmu...@gmail.com` on 2 Jan 2012 at 8:54
- Changed state: **Fixed**

Attachments:
- [fixed.png](https://storage.googleapis.com/google-code-attachments/armitage/issue-79/comment-13/fixed.png)
