### ISSUE TITLE
DNS enumeration in Armitage throwing a stack trace

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Kaicastledine/armitage#93]
```
What steps will reproduce the problem?
Using Hosts > DNS Enum in Armitage I get a stack trace.
The same module in the Metasploit console (no Armitage) works fine, which makes 
me believe it's an Armitage related issue.

What version of Metasploit are you using (type: svn info)? On which
operating system?
Svn r15017 updated 2012.03.23 on Mico$oft Windows 7.


Which database are you using?
Postgresql.


```

Original issue reported on code.google.com by `houcem.h...@gmail.com` on 25 Mar 2012 at 3:55

Attachments:
- [Armitage-DNS-Enumerate.png](https://storage.googleapis.com/google-code-attachments/armitage/issue-93/comment-0/Armitage-DNS-Enumerate.png)

**Comment by GoogleCodeExporter** [comment]
```
Would you be willing to try this same module in msfgui? I suspect it might be 
an RPC or MessagePack issue. 
```

Original comment by `rsmu...@gmail.com` on 25 Mar 2012 at 7:16

**Comment by GoogleCodeExporter** [comment]
```
Got the same error in msfgui.
```

Original comment by `houcem.h...@gmail.com` on 25 Mar 2012 at 7:26

Attachments:
- [msfgui_2012-03-25_20-23-49.png](https://storage.googleapis.com/google-code-attachments/armitage/issue-93/comment-2/msfgui_2012-03-25_20-23-49.png)

**Comment by GoogleCodeExporter** [comment]
```
Now, if you can reproduce the problem in Metasploit Pro/Express/Community 
edition, then we can get Rapid7 to fix it :D
```

Original comment by `rsmu...@gmail.com` on 25 Mar 2012 at 9:04

**Comment by GoogleCodeExporter** [comment]
```
This looks like an issue with the win32-registry gem more than anything else, 
looking into it, but there is a good chance an update gem in next week's 
release will resolve it.
```

Original comment by `x...@hdm.io` on 19 Apr 2012 at 8:24

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
anyway you can copypaste your text into the bug directly, rather than just the 
screen? That way search engines can crawl your error message and help future 
generations of Windows rubyists.
```

Original comment by `t...@packetfu.com` on 19 Apr 2012 at 8:39

**Comment by GoogleCodeExporter** [comment]
```
msf  auxiliary(enum_dns) > run -j
[*] Auxiliary module running as background job
[-] Auxiliary failed: ArgumentError unknown encoding name - CP0
[-] Call stack:
[-]   C:/metasploit/ruby/lib/ruby/1.9.1/win32/registry.rb:172:in `find'
[-]   C:/metasploit/ruby/lib/ruby/1.9.1/win32/registry.rb:172:in `initialize'
[-]   C:/metasploit/ruby/lib/ruby/1.9.1/win32/registry.rb:231:in `exception'
[-]   C:/metasploit/ruby/lib/ruby/1.9.1/win32/registry.rb:231:in `raise'
[-]   C:/metasploit/ruby/lib/ruby/1.9.1/win32/registry.rb:231:in `check'
[-]   C:/metasploit/ruby/lib/ruby/1.9.1/win32/registry.rb:284:in `QueryValue'
[-]   C:/metasploit/ruby/lib/ruby/1.9.1/win32/registry.rb:587:in `read'
[-]   C:/metasploit/ruby/lib/ruby/1.9.1/win32/registry.rb:637:in `read_s'
[-]   C:/metasploit/ruby/lib/ruby/1.9.1/win32/resolv.rb:72:in `block in 
get_info'
[-]   C:/metasploit/ruby/lib/ruby/1.9.1/win32/registry.rb:389:in `open'
[-]   C:/metasploit/ruby/lib/ruby/1.9.1/win32/registry.rb:496:in `open'
[-]   C:/metasploit/ruby/lib/ruby/1.9.1/win32/resolv.rb:62:in `get_info'
[-]   C:/metasploit/ruby/lib/ruby/1.9.1/win32/resolv.rb:20:in `get_resolv_info'
[-]   C:/metasploit/msf3/lib/net/dns/resolver.rb:1032:in `parse_config_file'
[-]   C:/metasploit/msf3/lib/net/dns/resolver.rb:226:in `initialize'
[-]   C:/metasploit/msf3/modules/auxiliary/gather/enum_dns.rb:468:in `new'
[-]   C:/metasploit/msf3/modules/auxiliary/gather/enum_dns.rb:468:in `run'
msf  auxiliary(enum_dns) > 
```

Original comment by `houcem.h...@gmail.com` on 19 Apr 2012 at 8:42

**Comment by GoogleCodeExporter** [comment]
```
Has this issue been resolved with the latest ship of MSF 4.3.0?
```

Original comment by `rsmu...@gmail.com` on 10 May 2012 at 8:17

**Comment by GoogleCodeExporter** [comment]
```
I'm running MSF 4.4.0 dev and I confirm that the issue is resolved.
```

Original comment by `houcem.h...@gmail.com` on 10 May 2012 at 8:28

**Comment by GoogleCodeExporter** [comment]
```
You're a good man. Thanks for the response!
```

Original comment by `rsmu...@gmail.com` on 10 May 2012 at 8:46
- Changed state: **WontFix**
