### ISSUE TITLE
Metasploit RPC daemon Shut Down

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Kaicastledine/armitage#95]
```
What steps will reproduce the problem?
1.Open Armitage
2.Click on connect

What is the expected output? What do you see instead?
it suppose to open armitage window


What version of Metasploit are you using (type: svn info)? On which
operating system?
metasploit v4.3.0 on Backtrack 5 R1








```

Original issue reported on code.google.com by `atef.na...@gmail.com` on 7 Apr 2012 at 10:44

Attachments:
- [Capture.PNG](https://storage.googleapis.com/google-code-attachments/armitage/issue-95/comment-0/Capture.PNG)

**Comment by GoogleCodeExporter** [comment]
```
This is not a bug. This is my best attempt to help you. msfrpcd is crashing for 
some reason when Armitage tries to start it. Here's what you do:

1. Follow the troubleshooting steps by clicking Yes. Make sure you're running 
BackTrack 5r2 (or 5r1) without any upgrades to the system itself. msfupdate is 
OK.

2. If those don't work, then do the following:

msfrpcd -U msf -P test -f
armitage

Connect to Metasploit on 127.0.0.1 with the username msf and the password test. 
See if the daemon dies. If it does, why? It'll give you an error. Paste the 
error here and I'll tell you what it means. If you don't provide that for me, I 
am not going to "guess" or offer any other help on this matter.
```

Original comment by `rsmu...@gmail.com` on 7 Apr 2012 at 2:10
- Changed state: **Invalid**

**Comment by GoogleCodeExporter** [comment]
```
when i do this msfrpcd -U msf -P test -f
it show me
[*] MSGRPC starting on 0.0.0.0:55553 (SSL):Msg...
[*] MSGRPC ready at 2012-04-07 16:28:46 +0100.
/opt/framework3/msf3/lib/fastlib.rb:368:in `require': no such file to load -- 
msgpack (MissingSourceFile)
    from /opt/framework3/msf3/lib/fastlib.rb:368:in `require'
    from /opt/framework3/msf3/lib/msf/core/rpc/v10/service.rb:1:in `<top (required)>'
    from /opt/framework3/msf3/lib/fastlib.rb:368:in `require'
    from /opt/framework3/msf3/lib/fastlib.rb:368:in `require'
    from /opt/framework3/msf3/plugins/msgrpc.rb:14:in `<top (required)>'
    from /opt/framework3/msf3/lib/fastlib.rb:368:in `require'
    from /opt/framework3/msf3/lib/fastlib.rb:368:in `require'
    from /opt/framework3/msf3/lib/msf/core/plugin_manager.rb:51:in `load'
    from /opt/framework3/msf3/lib/msf/base/simple/framework.rb:31:in `load'
    from /opt/framework3/msf3/msfrpcd:110:in `<main>'
```

Original comment by `atef.na...@gmail.com` on 7 Apr 2012 at 4:32

**Comment by GoogleCodeExporter** [comment]
```
Armitage 11.13.11 and later have new dependencies. You must install Metasploit 
4.0 or greater using the full setup installer. The one with all of the 
dependencies. msfupdate does not update your environment.

Your environment *is* out of date.

Get BackTrack 5r2 or uninstall Metasploit and renstall Metasplooit from the 
full installer.

Read http://www.fastandeasyhacking.com/nomsfrpcd for the full back story and 
all of the details if you'd like an explanation. 
```

Original comment by `rsmu...@gmail.com` on 7 Apr 2012 at 5:02

**Comment by GoogleCodeExporter** [comment]
```
How can i remove metasploit from backtrack ??
```

Original comment by `atef.na...@gmail.com` on 7 Apr 2012 at 5:17

**Comment by GoogleCodeExporter** [comment]
```
http://bit.ly/Ilrzec
```

Original comment by `rsmu...@gmail.com` on 7 Apr 2012 at 5:47

**Comment by GoogleCodeExporter** [comment]
```
Solved ;) thx a lot
```

Original comment by `atef.na...@gmail.com` on 7 Apr 2012 at 8:49

**Comment by GoogleCodeExporter** [comment]
```
when i type msfrpcd -U msf -P test -f
armitage i got the following error 

[*] XMLRPC starting on 0.0.0.0:55553 (SSL):Basic...
/opt/metasploit3/msf3/msfrpcd:94:in `<main>': undefined method `restart' for 
nil:NilClass (NoMethodError)

Please help i have searched on youtube on the troubleshooting page on 
everything but nothing helps even msfgui didn't helps :-(
please help...
```

Original comment by `maudib...@gmail.com` on 26 Jul 2012 at 9:20

**Comment by GoogleCodeExporter** [comment]
```
@maudib112 - you are not following the instructions on fastandeasyhacking.com. 
No where do I say that using msfgui to start the Metasploit RPC daemon will 
help at all. The parameters you're using are wrong for how Armitage expects 
Metasploit's RPC daemon to be setup now.

Follow these instructions and these instructions only. YouTube videos go stale. 
It's much easier to keep the documentation up to date (and I do):

http://www.fastandeasyhacking.com/start
```

Original comment by `rsmu...@gmail.com` on 26 Jul 2012 at 2:43

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
im using windows7 and i m getting this :3
how can i solve it?
```

Original comment by `SsM...@gmail.com` on 18 Dec 2014 at 4:34

**Comment by GoogleCodeExporter** [comment]
```
open all the port in your router 443 80 55553 and...

```

Original comment by `mohamedd...@gmail.com` on 22 Feb 2015 at 11:49
